### ISSUE TITLE
[FEATURE REQUEST] Updating to python 3.10

### ISSUE THREAD

**Issue by vladtrc** [CAMeL-Lab/camel_tools#99]
I dont think updating to a 3.10 would be a major pain. Is it possible? Are there any obvoius blockers?

**Comment by GuillemGSubies** [comment]
I would really appreciate support for python 3.10 too

**Comment by YazanShannak** [comment]
Are there any updates on this?

**Comment by owo** [comment]
Python 3.10 is now supported in the latest release.

Make sure to do `pip install --upgrade --force-reinstall camel-tools` and update any pre-downloaded packages (e.g. `camel_data -u && camel_data -i -f all`)

**Comment by YazanShannak** [comment]
@owo 
I still have a problem installing camel-tools on python3.10 with the latest release, here's the log:

```
× Building wheel for camel-kenlm (pyproject.toml) did not run successfully.                                                                                                                 
  │ exit code: 1                        
  ╰─> [78 lines of output]                                                                     
      Will build with KenLM max_order set to 6                                                                                                                                                
      running bdist_wheel                                                                      
      running build                                                                                                                                                                           
      running build_ext                                                                        
      -- The C compiler identification is GNU 11.3.0                                                                                                                                          
      -- The CXX compiler identification is GNU 11.3.0                                         
      -- Detecting C compiler ABI info                                                                                                                                                        
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped                                                                                                                                  
      -- Detecting C compile features          
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Could NOT find Eigen3 (missing: Eigen3_DIR)
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      CMake Error at /tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find Boost (missing: Boost_INCLUDE_DIR program_options system
        thread unit_test_framework) (Required is at least version "1.41.0")
      Call Stack (most recent call first):
        /tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
        /tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/cmake/data/share/cmake-3.26/Modules/FindBoost.cmake:2377 (find_package_handle_standard_args)
        CMakeLists.txt:97 (find_package)

-- Configuring incomplete, errors occurred!                                                                                                                                    [25/1815]
      Traceback (most recent call last):
        File "/home/yazansh/thesis/ara-correctra/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/yazansh/thesis/ara-correctra/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/yazansh/thesis/ara-correctra/venv/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 123, in <module>
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1221, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-8ei9ku0c/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 104, in run
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-install-pjg8m_55/camel-kenlm_27c5d7a08bde4dbfa7a773db05780bb3', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-install-pjg8m_55/
camel-kenlm_27c5d7a08bde4dbfa7a773db05780bb3/build/lib.linux-x86_64-cpython-310', '-DBUILD_SHARED_LIBS=ON', '-DBUILD_PYTHON_STANDALONE=OFF', '-DKENLM_MAX_ORDER=6', '-DCMAKE_BUILD_TYPE=Releas
e']' returned non-zero exit status 1.
      [end of output]
   
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for camel-kenlm
ERROR: Could not build wheels for camel-kenlm, which is required to install pyproject.toml-based projects

```

**Comment by owo** [comment]
You'll need to install [Boost](https://www.boost.org/) for one of our dependencies to build (this wasn't necessary before).

On Ubuntu you can install it by running `sudo apt install libboost-all-dev` or on macOS using homebrew by running `brew install boost`.

We're looking at ways to avoid users having to install this themselves. Hopefully this should be solved soon.

**Comment by YazanShannak** [comment]
Understood, I think this should be explicitly mentioned in the docs,
please let me know if I can contribute in any possible way

**Comment by owo** [comment]
I updated the installation instructions to address this. In the meantime, I'm looking for a workaround so that the extra dependencies wouldn't be necessary.

**Comment by ahmadabousetta** [comment]
I had to install "sudo apt install build-essentials" to solve the cmake build issue.
It works fine now. Hope this helps anyone.
